#ifndef LIBRARYSEARCHINGPROJECT_GLOBAL_H
#define LIBRARYSEARCHINGPROJECT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBRARYSEARCHINGPROJECT_LIBRARY)
#  define LIBRARYSEARCHINGPROJECT_EXPORT Q_DECL_EXPORT
#else
#  define LIBRARYSEARCHINGPROJECT_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBRARYSEARCHINGPROJECT_GLOBAL_H
